project_id = "vaxhehwnfkhdmprundau"

[functions.send-otp-email]
verify_jwt = false

[functions.confirm-user-email]
verify_jwt = false

[functions.create-account-application]
verify_jwt = false

[functions.resend-all-verifications]
verify_jwt = false

[functions.create-test-account]
verify_jwt = false

[functions.support-bot]
verify_jwt = false

[functions.create-admin-account]
verify_jwt = false

[functions.delete-test-users]
verify_jwt = false

[functions.delete-unverified-users]
verify_jwt = true

[functions.send-login-otp]
verify_jwt = false
