project_id = "vaxhehwnfkhdmprundau"

[functions.create-account-application]
verify_jwt = false

[functions.resend-all-verifications]
verify_jwt = false

[functions.create-test-account]
verify_jwt = false
